n1 = int(input("Introduce el primer número:"))
n2 = int(input("Introduce el segundo número:"))

print("Suma:", n1 + n2)
print("Resta:", n1 - n2)
print("Multiplicación:", n1 * n2)
print("División:", n1 / n2)
print("- 2 -")
print("Suma:", n1 + n2)
print("Suma:", n1 + n2)
print("Suma:", n1 + n2)
print("Suma:", n1 + n2)
print("Suma:", n1 + n2)
print("Suma:", n1 + n2)
print("Suma:", n1 + n2)
print("Suma:", n1 + n2)